#!/usr/bin/env ruby

require 'optparse'
require_relative '../lib/tryouts'

# Add local lib directories to the load path
Dir.glob(File.join(Dir.pwd, '{lib,..,lib}')).each { |dir| $LOAD_PATH.unshift(dir) }

# Parse command-line arguments
options = { quiet: false, noisy: false, fails: false }
OptionParser.new do |opts|
  opts.on('-V', '--version', 'Display the version') { puts "Tryouts: #{Tryouts::VERSION}"; exit }
  opts.on('-q', '--quiet', 'Run in quiet mode') { options[:quiet] = true }
  opts.on('-v', '--verbose', 'Run in verbose mode') { options[:noisy] = true }
  opts.on('-f', '--fails', 'Show only failing tryouts') { options[:fails] = true }
  opts.on('-D', '--debug', 'Run in debug mode') { Tryouts.debug = true }
  opts.on('-h', '--help', 'Display this help') { puts opts; exit }
end.parse!

# Set Tryouts options
Tryouts.quiet = options[:quiet]
Tryouts.noisy = options[:noisy]
Tryouts.fails = options[:fails]

# Determine tryout file paths
if ARGV.empty?
  paths = Dir.glob(File.join(Dir.pwd, '{try,tryouts}', '*_{try,tryouts}.rb'))
  paths += Dir.glob(File.join(Dir.pwd, '*_{try,tryouts}.rb'))
else
  paths = ARGV
end

exit Tryouts.run_all(*paths)
