name: CI

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

permissions:
  contents: read

jobs:
  basic-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Basic Tests (Ruby ${{ matrix.ruby }})
    strategy:
      fail-fast: true
      matrix:
        ruby: ["3.4", "3.5"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false

      - name: Configure bundle groups
        run: bundle config set --local with 'test development'

      - name: Install dependencies
        run: bundle install

      - name: Run basic proof tests
        run: ruby exe/try try/proof*_try.rb

  framework-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Framework Tests (Ruby ${{ matrix.ruby }})
    strategy:
      fail-fast: true
      matrix:
        ruby: ["3.4", "3.5"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false

      - name: Configure bundle groups
        run: bundle config set --local with 'test development'

      - name: Install dependencies
        run: bundle install

      - name: Run framework unit tests with coverage
        run: COVERAGE=1 ruby exe/try test/*_try.rb

  examples:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Examples (Ruby ${{ matrix.ruby }})
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.4", "3.5"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false

      - name: Configure bundle groups
        run: bundle config set --local with 'test development'

      - name: Install dependencies
        run: bundle install

      - name: Run example demonstrations (may fail intentionally)
        run: ruby exe/try examples/test_*.rb

  cli-options:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: CLI Options Test (Ruby ${{ matrix.ruby }})
    strategy:
      fail-fast: true
      matrix:
        ruby: ["3.4", "3.5"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false

      - name: Configure bundle groups
        run: bundle config set --local with 'test development'

      - name: Install dependencies
        run: bundle install

      - name: Test version flag
        run: ruby exe/try -V

      - name: Test verbose mode
        run: ruby exe/try -v try/proof1_try.rb

      - name: Test debug mode
        run: ruby exe/try -D try/proof1_try.rb

      - name: Test verbose failures
        run: ruby exe/try -vf try/proof1_try.rb

      - name: Test quiet mode
        run: ruby exe/try -q try/proof1_try.rb
