name: CI

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

permissions:
  contents: read

jobs:
  core:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    name: "Tryouts: ${{ matrix.testgroup }} (Ruby ${{ matrix.ruby }})"
    strategy:
      fail-fast: true
      matrix:
        ruby: ["3.4", "3.5"]
        testgroup: [core, expectations, formatters, translators]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false

      - name: Configure bundle groups
        run: bundle config set --local with 'test development'

      - name: Install dependencies
        run: bundle install

      - name: Run framework unit tests with coverage
        run: COVERAGE=1 bundle exec exe/try ${{ matrix.testgroup }}

  cli-options:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    name: CLI Options Test (Ruby ${{ matrix.ruby }})
    strategy:
      fail-fast: true
      matrix:
        ruby: ["3.4", "3.5"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false

      - name: Configure bundle groups
        run: bundle config set --local with 'test development'

      - name: Install dependencies
        run: bundle install

      - name: Test version flag
        run: bundle exec exe/try -V

      - name: Test verbose mode
        run: bundle exec exe/try -v try/core/advanced_syntax_try.rb

      - name: Test debug mode
        run: bundle exec exe/try -D try/core/advanced_syntax_try.rb

      - name: Test verbose failures
        run: bundle exec exe/try -vf try/core/advanced_syntax_try.rb

      - name: Test quiet mode
        run: bundle exec exe/try -q try/core/advanced_syntax_try.rb
