name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        include:
          - ruby: '3.3'
            bundler: latest
            rubygems: latest

          - ruby: '3.2'
            bundler: latest
            rubygems: latest

          - ruby: '3.1'
            bundler: latest
            rubygems: latest

          - ruby: '3.0'
            bundler: latest
            rubygems: latest

          - ruby: '2.7'
            bundler: '2.4.22'
            rubygems: '3.2.3'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        rubygems: ${{ matrix.rubygems }}
        bundler: ${{ matrix.bundler }}
        bundler-cache: true

    - name: Run the tryouts
      run: bundle exec try -v try/*_try.rb
